[package]
name = "monster-rs"
description = "Monster is a symbolic execution engine for 64-bit RISC-U code"
authors = ["Alexander Lackner <monster@a.lfweb.org>", "Alexander Linz <linzalexander@gmail.com>", "Christian Mösl <christian.moesl@live.at>", "Fabian Nedoluha <monster@onders.org>"]
documentation = "https://docs.rs/monster"
repository = "https://github.com/cksystemsgroup/monster"
homepage = "https://cksystemsgroup.github.io/monster"
license = "MIT"
categories = ["command-line-utilities", "development-tools::testing", "science", "simulation"]
keywords = ["monster", "riscv", "riscu", "symbolic-execution", "smt"]
edition = "2018"
version ="0.1.0"

[features]
default = []
boolector-solver = ["boolector"]
z3-solver = ["z3"]

[lib]
name = "monster"
path = "src/lib.rs"

[[bin]]
name = "monster"
path = "src/main.rs"

[dependencies]
byteorder = "~1.4.2"
clap = "3.0.0-beta.2"
riscu = "~0.5.0"
petgraph = "~0.5.1"
rand = "~0.7.3"
modinverse = "~0.1.1"
log = "~0.4.11"
env_logger = "~0.8.1"
bytesize = "~1.0.1"
itertools = "~0.9.0"
anyhow = "~1.0.34"
thiserror = "~1.0.22"
divisors = "~0.2.1"
const_format = "~0.2.13"
boolector = { version = "~0.4.2", features = ["vendor-lgl"], optional = true }
z3 = { version = "~0.7.1", features = ["static-link-z3"], optional = true }

[dev-dependencies]
rayon = "~1.5.0"
tempfile = "~3.1.0"
which = "~4.0.2"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]
